version: '3'

services:
  etcd-server:
    image: bitnami/etcd:3.6.3
    environment:
      - ALLOW_NONE_AUTHENTICATION=yes
      - ETCD_ADVERTISE_CLIENT_URLS=http://etcd:2379
      - ETCD_ROOT_PASSWORD=changeMe
      - ETCD_LOG_LEVEL=warn
    volumes:
      - ./conf.yml:/opt/bitnami/Etcd/conf/etcd.conf.yml
    ports:
      - "2379:2379"
      - "2380:2380"
