version: "3.1"

services:
  mysql-server:
    container_name: mysql-server-8
    image: "mysql:8.0.23"
    command: >
      mysqld --lower-case-table-names=1 --sql-mode="" --default-time-zone="+08:00" --innodb_buffer_pool_size=1073741824 --max_allowed_packet=134217728 --bulk_insert_buffer_size=536870912 --local_infile="on" --binlog_expire_logs_seconds=604800 --skip-name-resolve
    environment:
      - MYSQL_ROOT_PASSWORD=CHANGE_ME
      - MYSQL_DATABASE=default
    ports:
      - "33060:3306"
    restart: always
    volumes:
      - ./data/data/mysql:/var/lib/mysql:delegated
      - ./data/config/mysql:/etc/mysql/conf.d:delegated
      - ./data/logs/mysql:/var/log/mysql:delegated