version: "3.1"

services:
  minio:
    image: "minio/minio"
    container_name: minio
    network_mode: "host"
    volumes:
      - ./data/data:/data
      - ./data/config:/root/.minio
    command: server /data --console-address ":9001"
    environment:
      - MINIO_ROOT_USER=CHANGE_ME
      - MINIO_ROOT_PASSWORD=CHANGE_ME
    ports:
      - "9000:9000"
      - "9001:9001"
    restart: always